openapi: 3.0.0
info:
  title: Minha API
  description: E-Commerce, or electronic commerce, is a system of
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Costumer
    description: Everything about costumer
paths:
  /login:
    post:
      summary: Rota de login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token JWT gerado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '403':
          description: Informações de autorização ausentes ou inválidas.
        '404':
          description: Usuário com o ID especificado não encontrado.
        '5XX':
          description: Erro inesperado.
  /users:
    get:
      summary: Buscar dados protegidos
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dados obtidos com sucesso
          content:
            application/json:
              schema:
                type: array
                properties:
                  data:
                    type: object


        '403':
          description: Informações de autorização ausentes ou inválidas.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
